---
version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
# Supposedly dependabot breaks when using Poetry 2.
#  - package-ecosystem: "pip"
#    directory: "/"
#    schedule:
#      interval: "daily"
