---
name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  dispatch-command:
    runs-on: ubuntu-latest
    steps:
      - name: Slash Command Dispatch
        uses: peter-evans/slash-command-dispatch@13bc09769d122a64f75aa5037256f6f2d78be8c4 # v4
        with:
          token: ${{ secrets.PAT }}
          commands: |
            vc
            help
          issue-type: pull-request
          permission: none
